### PR TITLE
Update ssoauthhelper.ts

### PR DESCRIPTION
**Pull request by dubbs**
There is an issue with `npm run build` in environments respecting filename case sensitivity.   To fix the build, all we needed to do was update the `fallbackauthhelper` import.

### CODE REVIEW

**Comment by lindalu-MSFT** [comment]
@OfficeDev/office-platform-devx Hey can someone approve and merge this PR? Seems like a straightforward fix. Thanks, linda

**Review by millerds — APPROVED** [review]

**Comment by lindalu-MSFT** [comment]
Hey Darren, is there anything else I need to do to merge my changes to the other templates or does this command do that? Thanks!


Regards,

Linda
Please forgive odd mistakes. I may have dictated this message.

**Comment by millerds** [comment]
That command was trying to get the verification test to kick off (they seem to be stuck).

This shouldn't affect the verifications at all so I can by pass that and have this merged into this project.  The merging into the other project templates is a process we have to do manually when we feel a need to make those updates (batching up changes).  That will come after this project is updated.

**Pull request merged**
